version: '3'
services:
  mariadb:
    image: docker.uclv.cu/bitnami/mariadb:10.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.uclv.cu/bitnami/moodle:3
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local-persist
    driver_opts:
      mountpoint: /home/cpalacios/dockering/docker_moodle_elinf/mariadb_data
  moodle_data:
    driver: local-persist
    driver_opts:
      mountpoint: /home/cpalacios/dockering/docker_moodle_elinf/moodle_data
  moodledata_data:
    driver: local-persist
    driver_opts:
      mountpoint: /home/cpalacios/dockering/docker_moodle_elinf/moodledata_data
